auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ZhixinLiu.com
url: http://ZhixinLiu.com
feed: /atom.xml
author_info: <a href="http://www.zhixinliu.com/">Zhixin Liu</a>
